services:
  db:
    image: postgres:17-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build: .
    command: ./entrypoint.sh
    ports:
      - 8000:8000

  client:
    build: ./client
    ports:
      - 3000:80

volumes:
  database:
